### ISSUE TITLE
Pip installs stomp.py 5.0.0 and newer on Python 2.7

### ISSUE THREAD

**Issue by andy-maier** [jasonrbriggs/stomp.py#279]
Problem:

stomp.py 5.0.0 removed support for Python 2.7, but that is not properly indicated in the pacjage metadata. Therefore, pip installs stomp.py 5.0.0 and higher happily on Python 2.7.

Solution:

To constrain the Python version, it is not sufficient to just set the Python version in the `classifiers` argument of `setuptools.setup()`.

In addition, the `python_requires` argument needs to be specified, e.g. as follows:
```
python_requires='>=3.4',
```
or whatever the minimum Python 3.x version is supposed to be.

As far as I know, the `classifiers` argument does not necessarily have to be exactky consistent with that, so it can either continue to be a single classifier for Python 3, or in addition a list of classifiers for each supported Python 3.x version.

**Comment by andy-maier** [comment]
Addressed in PR #280.

**Comment by jasonrbriggs** [comment]
Resolved on the dev branch.

**Comment by vphilippon** [comment]
The issue is still present, and fixing the metadata in a future release won't resolve the issue.
Py2.7 users will still pick up `stomp.py 5.0.1`, which still won't be Py2.7-compatible.

The best option I can see to help Py2.7 users here would be to release `stomp.py 5.0.2` with the exact content `stomp.py 4.1.23`, which was the latest to support Py2.7,
and then release `stomp.py 6.0.0` (or `5.0.3`), with the same content as `stomp.py 5.0.1`, but this time with the `python_requires='>=3.4'` metadata.

It's a bit of a revert-and-redo gymnastic, but I can't offer much other solution other than removing some releases of pypi, which is always a mess.

**Comment by jasonrbriggs** [comment]
@vphilippon  Out of sheer laziness, I went with removing the two 5.x.x versions and then releasing a new 6.0.0 version.  As far as I can see it's working (pip install stomp.py results in 4.1.23 with python2.7 and 6.0.0 with py3).
